# OpenLDAP, PHPldapadmin and Passreset stack.

version: '3'
services:

  openldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: secret
    ports:
      - 389:389

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 5000:80
    depends_on:
      - openldap

  passreset:
    image: vfabi/passreset:latest
    #env_file:
    #  - env.dockercompose
    environment:
      #EMAIL_TRANSPORT: email_server
      #EMAIL_SERVER_ADDRESS: "smtp.gmail.com"
      #EMAIL_SERVER_PORT: 465
      #EMAIL_SERVER_USER: gmailusername
      #EMAIL_SERVER_PASSWORD: gmailpassword
      EMAIL_TRANSPORT: aws_ses
      EMAIL_AWSSES_ACCESS_KEY: yyyyyyyyyyyyy
      EMAIL_AWSSES_SECRET_KEY: zzzzzzzzzzzzz
      EMAIL_AWSSES_REGION: us-west-2
      EMAIL_AWSSES_SENDER: gmailusername@gmail.com
      BACKEND_TYPE: ldap
      LDAP_SERVER_ADDRESS: openldap
      LDAP_SERVER_USER: cn=admin,dc=example,dc=com
      LDAP_SERVER_PASSWORD: admin
      LDAP_SERVER_PORT: 389
      LDAP_SERVER_SEARCH_RDN: dc=example,dc=com
    ports:
      - 8000:8000
    depends_on:
      - openldap