# OpenLDAP, PHPldapadmin and Passreset stack for interconnectivity testing.

version: '3'
services:

  openldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: secret
    ports:
      - 389:389

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8000:80
    depends_on:
      - openldap

  passreset:
    image: vfabi/passreset:latest
    env_file:
      - env.dockercompose
    ports:
      - 5000:8000
    depends_on:
      - openldap
